spring.application.name=demoUploadFile
# CẤU HÌNH SERVER
server.port=8080
# CẤU HÌNH KẾT NỐI DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/demofile
# Tên đăng nhập (mặc định là root)
spring.datasource.username=root
# Mật khẩu (nhập đúng mật khẩu đã đặt khi cài MySQL)
spring.datasource.password=123456
# Driver class (MySQL 8 dùng driver này)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
cloudinary.cloud-name=mdhehnzf
cloudinary.api-key=733722358161451
cloudinary.api-secret=rQl5mOYWFbIn7w0kHCea_wa6y-A